#!/usr/bin/env bash

## By Davoud Arsalani
##    https://github.com/davoudarsalani/scripts
##    https://github.com/davoudarsalani/scripts/blob/master/awesome-autorun
##    https://raw.githubusercontent.com/davoudarsalani/scripts/master/awesome-autorun
##    https://davoudarsalani.ir

source "$HOME"/main/scripts/gb

autorun_file=/tmp/autorun
[ -f "$autorun_file" ] && exit || touch "$autorun_file"

## tricks for the time when power saving screws audio
# printf '0\n' | sudo tee /sys/module/snd_hda_intel/parameters/power_save
# printf 'N\n' | sudo tee /sys/module/snd_hda_intel/parameters/power_save_controller
# sleep 2

# pulseaudio -k && \
# pulseaudio -D && \
# sleep .1
## previously (ditched after moving to SSD):
# pulseaudio --start &

start-pulseaudio-x11 || msgc "start-pulseaudio-x11 failed"

source "$HOME"/main/scripts/gb-audio
while (( vol_level != 30 )); do
    printf 'tried to set volume to 30 at %s\n' "$(get_datetime 'jymdhms')" >> /tmp/vol_30  ## just to keep record of how many times the loop tried
    pactl set-sink-volume "$def_sink_index" 30%
    source "$HOME"/main/scripts/gb-audio
    sleep 1
done
msgn 'Volume set to 30'
audacious "$HOME"/main/linux/sounds/login_mint.ogg &

# source "$HOME"/main/scripts/gb-screen
# xrandr --output  "$scr_1_name" --mode 1366x768 --rate 60 --primary
# xrandr --addmode "$scr_2_name" 1600x900
# xrandr --output  "$scr_2_name" --mode 1600x900 --rate 60 --right-of "$scr_1_name"
# xrandr --output  "$scr_2_name" --gamma .85:1:1.14  ## + custom mode (80 100 75)
# xrandr --output  "$scr_2_name" --gamma .65:1:.9    ## + standard mode

nm-applet &
greenclip daemon &
picom -b &


## key logger
# current_date="$(get_datetime 'jymd')"
# "$HOME"/main/scripts/.venv_keylogger/bin/python3 "$HOME"/main/scripts/.venv_keylogger/bin/keylogger --log-file "$HOME"/main/linux/keylogs/keylog-"$current_date" &


# source "$HOME"/main/scripts/gb-network
# [ "$eth_ip" ] || {
#    add_desired_ip_to_ethernet
#    msgn "added <span color=\"${orange}\">${desired_eth_ip}</span> to <span color=\"${orange}\">${eth_devc}</span>"
# }

widgets=(
    'audio'
    'firewall'
    'brightness'
    'bluetooth'
    'clipboard'
    'klgr'  ## it is updated regularly with watch, but this had better be here too
    'tor'
    'turn_off_scr_3'
    # 'move_screen_2_to_left'
)

for widget in "${widgets[@]}"; {
    "$HOME"/main/scripts/awesome-widgets "$widget"
    sleep .1
}

msgn ' ' ' ' "$HOME"/main/linux/themes/ok-w.png
