#!/usr/bin/env bash
source $HOME/scripts/gb

function now(){
    if_speech
    copy_pacman_log
    copy_random_wallpaper_for_startup
    play_shutdown_track

    [ "$3" == "cc" ] && clear_clipboard
    case "$1" in
        pc ) if   [ "$2" == "shutdown" ]; then
                 shutdown -h now
             elif [ "$2" == "reboot" ]; then
                 shutdown -r now
             fi ;;
        awesome ) if   [ "$2" == "quit" ]; then
                      echo -e 'awesome.quit()' | awesome-client
                  elif [ "$2" == "restart" ]; then
                      echo -e 'awesome.restart()' | awesome-client  ## do NOT remove the () in restart. [Originally, () is not required in rc.lua]
                  fi ;;
    esac ;}

case "$1" in
    ## app_menu
    audacious )         audacious & ;;
    blueman_applet )    blueman-applet 1>/dev/null 2>&1 & ;;
    blueman_manager )   blueman-manager 1>/dev/null & ;;
    calculator )        gnome-calculator & ;;
    chromium )          chromium 1>/dev/null 2>&1 & ;;
    disks )             gnome-disks & ;;
    firefox )           firefox 1>/dev/null 2>&1 & ;;
    gedit )             gedit 2>/dev/null & ;;
    gimp )              gimp 2>/dev/null & ;;
    goldendict )        goldendict 1>/dev/null 2>&1 & ;;
    gparted )           sudo gparted 1>/dev/null & ;;
    gpicview )          gpicview & ;;
    kdenlive )          kdenlive 2>/dev/null & ;;
    keepass )           keepass 2>/dev/null & ;;
    kid3 )              kid3 2>/dev/null & ;;
    lf )                "$terminal" -e "lf $HOME/downloads/" & ;;
    libreoffice )       libreoffice 2>/dev/null & ;;
    lxappearance )      lxappearance & ;;
    qutebrowser )       qutebrowser --target tab & ;;
    ranger )            "$terminal" -e "ranger $HOME/downloads/" & ;;
    terminal )          "$terminal" ;;
    terminal_tmux )     [ ! $(pgrep "tmux") ] && "$terminal" -e "tmux new -s 1" || "$terminal" -e "tmux new" ;;
    terminal_torsocks ) torsocks "$terminal" ;;
    uget )              uget-gtk 2>/dev/null & ;;
    vlc )               vlc 2>/dev/null & ;;
    xreader )           xreader 2>/dev/null & ;;
    ## off_menu
    shutdown )                         now pc shutdown ;;
    "shutdown + clear clipboard" )     now pc shutdown cc ;;
    reboot )                           now pc reboot ;;
    "reboot + clear clipboard" )       now pc reboot cc ;;
    lock )                             dm-tool lock ;;
    screen_off )                       xset dpms force off ;;
    "quit awesome" )                   now awesome quit ;;
    "quit awesome + clear clipboard" ) now awesome quit cc ;;
    "restart awesome" )                now awesome restart ;;
esac

exit
