#!/usr/bin/env bash

## last modified: 1400-09-14 12:12:25 +0330 Sunday

source "$HOME"/scripts/gb

autorun_file=/tmp/autorun
[ -f "$autorun_file" ] && exit || touch "$autorun_file"

## tricks for the time when power saving screws audio
# printf '0\n' | sudo tee /sys/module/snd_hda_intel/parameters/power_save
# printf 'N\n' | sudo tee /sys/module/snd_hda_intel/parameters/power_save_controller
# sleep 2

pulseaudio --start &
start-pulseaudio-x11

source "$HOME"/scripts/gb-audio
while (( vol_level != 30 )); do
    printf 'tried to set volume to 30 at %s\n' "$(get_datetime 'jymdhms')" >> /tmp/vol_30  ## just to keep record of how many times the loop tried
    pactl set-sink-volume "$def_sink_index" 30%
    source "$HOME"/scripts/gb-audio
    sleep 1
done
audacious "$HOME"/linux/sounds/login_mint.ogg &

# source "$HOME"/scripts/gb-screen
# xrandr --output  "$scr_1_name" --mode 1366x768 --rate 60 --primary
# xrandr --addmode "$scr_2_name" 1600x900
# xrandr --output  "$scr_2_name" --mode 1600x900 --rate 60 --right-of "$scr_1_name"
# xrandr --output  "$scr_2_name" --gamma .85:1:1.14  ## + custom mode (80 100 75)
# xrandr --output  "$scr_2_name" --gamma .65:1:.9    ## + standard mode

nm-applet &
greenclip daemon &
picom -b &

current_date="$(get_datetime 'jymd')"
"$HOME"/scripts/.venv_keylogger/bin/python3 "$HOME"/scripts/.venv_keylogger/bin/keylogger --log-file "$HOME"/linux/keylogs/keylog-"$current_date" &

# source "$HOME"/scripts/gb-network
# [ "$eth_ip" ] || {
#    add_desired_ip_to_ethernet
#    msgn "added <span color=\"${orange}\">${desired_eth_ip}</span> to <span color=\"${orange}\">${eth_devc}</span>"
# }

widgets=(
    'audio'
    'firewall'
    'brightness'
    'bluetooth'
    'clipboard'
    'klgr'  ## it is updated regularly with watch, but this had better be here too
    'tor'
    'turn_off_scr_3'
)

for widget in "${widgets[@]}"; {
    "$HOME"/scripts/awesome-widgets "$widget"
}

msgn ' ' ' ' "$HOME"/linux/themes/ok-w.png

exit
