#!/usr/bin/env bash
source "$HOME"/scripts/gb

bookmarks="$(cat "$HOME"/linux/cfg-firefox/bookmarks.html |\grep "HREF=" | \grep -vE "place:parent|place:type" | sed 's/" .*//;s/^.*"//g;s/\/$//g' | sort)"

case "$1" in
    firefox ) ff_items=( "new page" "new tab" "private" "safe mode" "preferences" "tor" "$bookmarks" )
              ff_item="$(pipe_to_dmenu "${ff_items[@]}" "firefox" "")" || exit 37

              case "$ff_item" in
                  "new page" ) firefox 1>/dev/null 2>&1 & ;;
                  "new tab" ) firefox --new-tab "https://gitlab.com" 1>/dev/null 2>&1 & ;;
                  private ) firefox --private-window 1>/dev/null 2>&1 & ;;
                  "safe mode" ) firefox --safe-mode 1>/dev/null 2>&1 & ;;
                  preferences ) firefox --preferences 1>/dev/null 2>&1 & ;;
                  tor ) x="$PWD"
                        cd "$HOME"/tor-browser_en-US && ./start-tor-browser.desktop 1>/dev/null 2>&1
                        cd "$x" ;;
                  * ) firefox "$ff_item" 1>/dev/null 2>&1 & ;;
              esac ;;
    chromium ) chr_items=( "new page" "new tab" "private" "$bookmarks" )
               chr_item="$(pipe_to_dmenu "${chr_items[@]}" "chromium" "")" || exit 37

               case "$chr_item" in
                   "new page" ) chromium 1>/dev/null 2>&1 & ;;
                   "new tab" ) chromium "https://gitlab.com" 1>/dev/null 2>&1 & ;;
                   private ) chromium --incognito 1>/dev/null 2>&1 & ;;
                   * ) chromium "$chr_item" 1>/dev/null 2>&1 & ;;
               esac ;;
    qb ) qb_items=( "new page" "$bookmarks" )
         qb_item="$(pipe_to_dmenu "${qb_items[@]}" "qutebrowser" "")" || exit 37

         case "$qb_item" in
             "new page" ) qutebrowser --target tab & ;;
             * ) qutebrowser "$qb_item" & ;;
                esac ;;
esac

exit
