#!/usr/bin/env bash
source "$HOME"/scripts/gb

## https://misc.flogisoft.com/bash/tip_colors_and_formatting

title="${0##*/}"
heading "$title"

main_items=( "all" "38;5;{0-255} (foreground)" "48;5;{0-255} (background)" "tput setaf" )
main_item="$(pipe_to_fzf "${main_items[@]}")" && wrap_fzf_choice "$main_item" || exit 37

case "$main_item" in
    all ) for clbg in 49 {40..47}; do  ## {40..47} {100..107} 49
              for clfg in {30..37} 90; do  ## {30..37} {90..97} 39
                  for attr in {0..4} 7 9; do
                      echo -en "\e[${attr};${clbg};${clfg}m ${attr};${clbg};${clfg} \e[0m "
                  done
                  echo
              done
              echo
          done
          echo "$(yellow Pattern:)    \"\033[0;49;39m <TEXT> \033[0m\"" ;;
    "38;5;{0-255} (foreground)" ) for clfg in {0..255}; do
                                      printf '\e[38;5;%dm %03d \e[0m' "$clfg" "$clfg"
                                  done
                                  echo
                                  echo "$(yellow Pattern:)    \"\033[38;5;39m <TEXT> \033[0m\"" ;;
    "48;5;{0-255} (background)" ) for clfg in {0..255}; do
                                      printf '\e[48;5;%dm %03d \e[0m' "$clfg" "$clfg"
                                  done
                                  echo
                                  echo "$(yellow Pattern:)    \"\033[48;5;39m <TEXT> \033[0m\"" ;;
    "tput setaf" ) ## https://unix.stackexchange.com/questions/269077/tput-setaf-color-table-how-to-determine-color-codes
                   function color(){
                       for c; do
                           printf '\e[48;5;%dm%03d' "$c" "$c"
                       done
                       printf '\e[0m \n' ;}

                   IFS=$' \t\n'
                   color {0..15}
                   for ((i=0; i<6; i++)); do
                       color $(seq "$(( "$i" * 36 + 16 ))" "$(( "$i" * 36 + 51 ))")  ## do NOT change quotes
                   done
                   color {232..255}
                   echo
                   echo "$(yellow Pattern:)    (tput setaf 0) <text> (tput sgr 0)" ;;
esac

exit
