#!/usr/bin/env bash

## last modified: 1400-09-02 23:12:01 +0330 Tuesday

source "$HOME"/scripts/gb-color

readarray -t files < <(find -mindepth 1 -maxdepth 1 -type f | cut -c 3- | sort)
declare -i total=0

for file in "${files[@]}"; {
    mime_type="$(file --mime-type "$file" -bL)"

    case "$mime_type" in
        text/* ) lines="$(wc -l < "$file")"
                 printf '%s\t%s\n' "$lines" "$file"
                 total+="$lines" ;;
    esac
}

printf '\n%s\t%s\n' "$(yellow "$total")" "$(yellow 'total')"

exit
