#!/usr/bin/env bash

## @last-modified 1400-09-30 12:00:49 +0330 Tuesday

source "$HOME"/scripts/gb
source "$HOME"/scripts/gb-color

declare -i total=0
readarray -t files < <(find . -mindepth 1 -maxdepth 1 -type f | cut -c 3- | sort)

for file in "${files[@]}"; {
    mime_type="$(file --mime-type "$file" -bL)"
    case "$mime_type" in
        text/*|application/json|application/csv|message/news )
            lines="$(wc -l < "$file")"
             printf '%s\t%s\n' "$(insert_comma "$lines")" "$file"
             total+="$lines" ;;
    esac
}

total_comma="$(insert_comma "$total")"
printf '\n%s\t%s\n' "$(yellow "$total_comma")" "$(yellow 'total')"
