#!/usr/bin/env bash

## By Davoud Arsalani
##    https://github.com/davoudarsalani/scripts
##    https://github.com/davoudarsalani/scripts/blob/master/dell
##    https://davoudarsalani.ir

## @last-modified 1401-07-26 09:47:33 +0330 Tuesday

source "$HOME"/scripts/gb

trap 'exit 0' INT  ## avoid 255 exit code when using options that connect with x2x

title="${0##*/}"

function display_help {
    source "$HOME"/scripts/.help
    dell_help
}

function upload {
    scp -r "$@" nnnn@dell-"$bed":"$HOME"/downloads && accomplished
}

function download {
    local all

    all="${@:0}"  ## turn array into str because shelccheck said: SC2145 (error): Argument mixes string and array. Use * or separate argument.
    scp -r nnnn@dell-"$bed":"$all" "$HOME"/downloads && accomplished
}

function connect {
    ssh -Y nnnn@dell-"$bed" && accomplished
}

function connect_plus_x2x {
    ssh -Y nnnn@dell-"$bed" 'x2x -west -to :0'
}

function rsync_ {
    ## NOTE remove trailing slash
    source_dir="${source_dir%/}"

    rsync -a --progress --delete "$source_dir" nnnn@dell-"$bed":
}

function prompt {
    for _ in "$@"; {
        case "$1" in
            -n ) name="${name:-"$(get_input 'Dir/file name')"}" ;;
        esac
        shift
    }
}

function get_opt {
    local options

    options="$(getopt --longoptions 'help,name:' --options 'hn:' --alternative -- "$@")"
    eval set -- "$options"
    while true; do
        case "$1" in
            -h|--help )
                display_help ;;
            -n|--name )
                shift
                name="$1" ;;
            -- )
                break ;;
        esac
        shift
    done
}

get_opt "$@"
heading "$title"

main_items=(
    'ethernet connect + x2x'
    'ethernet connect'
    'ethernet download'
    'ethernet upload'
    'ethernet rsync ~/linux'
    'ethernet rsync ~/scripts'
    'wifi connect + x2x'
    'wifi connect'
    'wifi download'
    'wifi upload'
    'wifi rsync ~/linux'
    'wifi rsync ~/scripts'
    'help'
)

main_item="$(pipe_to_fzf "${main_items[@]}")" && wrap_fzf_choice "$main_item" || exit 37

case "$main_item" in
    'ethernet connect + x2x' )
        bed='ethernet'
        connect_plus_x2x ;;
    'ethernet connect' )
        bed='ethernet'
        connect ;;
    'ethernet download' )
        prompt -n
        bed='ethernet'
        download "$name" ;;
    'ethernet upload' )
        prompt -n
        bed='ethernet'
        upload "$name" ;;
    'ethernet rsync ~/linux' )
        bed='ethernet'
        source_dir="$HOME"/linux  ## NOTE JUMP_1 no trailing slash
        rsync_ ;;
    'ethernet rsync ~/scripts' )
        bed='ethernet'
        source_dir="$HOME"/scripts  ## JUMP_1
        rsync_ ;;

    'wifi connect + x2x' )
        bed='wifi'
        connect_plus_x2x ;;
    'wifi connect' )
        bed='wifi'
        connect ;;
    'wifi download' )
        prompt -n
        bed='wifi'
        download "$name" ;;
    'wifi upload' )
        prompt -n
        bed='wifi'
        upload "$name" ;;
    'wifi rsync ~/linux' )
        bed='wifi'
        source_dir="$HOME"/linux  ## JUMP_1
        rsync_ ;;
    'wifi rsync ~/scripts' )
        bed='wifi'
        source_dir="$HOME"/scripts  ## JUMP_1
        rsync_ ;;
    help )
        display_help ;;
esac
