#!/usr/bin/env bash
source "$HOME"/scripts/gb

case "$1" in
     goldendict ) if [ ! "$2" ]; then
                      gold_items=( 'open' )
                  elif [ "$2" == 'words' ]; then
                      readarray -t words < "$HOME"/bgls/words
                      gold_items=( 'open' '' "${words[@]}" )
                  fi

                  gold_item="$(pipe_to_rofi "${gold_items[@]}" 'goldendict' '')" || exit 37
                  case "$gold_item" in
                      open ) goldendict              &>/dev/null & ;;
                      * )    goldendict "$gold_item" &>/dev/null & ;;
                  esac ;;
esac

exit
