#!/usr/bin/env bash

## @last-modified 1400-09-10 21:48:16 +0330 Wednesday

source "$HOME"/scripts/gb

gold_items=( 'open' )

case "$1" in
     goldendict ) [ "$2" == 'words' ] && {
                      readarray -t words < "$HOME"/bgls/words
                      gold_items+=( '' "${words[@]}" )
                  }

                  gold_item="$(pipe_to_rofi "${gold_items[@]}" 'header=goldendict')" || exit 37

                  case "$gold_item" in
                      open ) goldendict              &>/dev/null & ;;
                      * )    goldendict "$gold_item" &>/dev/null & ;;
                  esac ;;
esac

exit
