#!/usr/bin/env bash

## By Davoud Arsalani
##    https://github.com/davoudarsalani/scripts
##    https://github.com/davoudarsalani/scripts/blob/master/gb-screen
##    https://davoudarsalani.ir

## @last-modified 1401-07-11 09:31:09 +0330 Monday

xrandr_output="$(xrandr)"

screens_count="$(wc -l < <(printf '%s\n' "$xrandr_output" | \grep -iw connected | \grep '[0-9]\{3,4\}x[0-9]\{3,4\}'))"
## OR <--,-- xrandr --listmonitors | sed '1q;d' | awk '{print $NF}'
##       '-- awesome-client 'return screen.count()' | awk '{print $NF}'

scr_1_name="$(printf '%s\n' "$xrandr_output" | \grep -iw 'connected' | \grep -i  'primary'              | awk '{print $1}')"
scr_2_name="$(printf '%s\n' "$xrandr_output" | \grep -iw 'connected' | \grep -iv 'primary' | sed '1q;d' | awk '{print $1}')"
scr_3_name="$(printf '%s\n' "$xrandr_output" | \grep -iw 'connected' | \grep -iv 'primary' | sed '2q;d' | awk '{print $1}')"

scr_1_res="$(printf '%s\n' "$xrandr_output"  | \grep "^$scr_1_name" | awk '{print $4}' | cut -d '+' -f 1)"
scr_1_x="$(printf '%s\n' "$xrandr_output"    | \grep "^$scr_1_name" | awk '{print $4}' | cut -d '+' -f 1 | cut -d 'x' -f 1)"
scr_1_y="$(printf '%s\n' "$xrandr_output"    | \grep "^$scr_1_name" | awk '{print $4}' | cut -d '+' -f 1 | cut -d 'x' -f 2)"

scr_2_res="$(printf '%s\n' "$xrandr_output"  | \grep "^$scr_2_name" | awk '{print $3}' | cut -d '+' -f 1)"
scr_2_x="$(printf '%s\n' "$xrandr_output"    | \grep "^$scr_2_name" | awk '{print $3}' | cut -d '+' -f 1 | cut -d 'x' -f 1)"
scr_2_y="$(printf '%s\n' "$xrandr_output"    | \grep "^$scr_2_name" | awk '{print $3}' | cut -d '+' -f 1 | cut -d 'x' -f 2)"

scr_3_res="$(printf '%s\n' "$xrandr_output"  | \grep "^$scr_3_name" | awk '{print $3}' | cut -d '+' -f 1)"
scr_3_x="$(printf '%s\n' "$xrandr_output"    | \grep "^$scr_3_name" | awk '{print $3}' | cut -d '+' -f 1 | cut -d 'x' -f 1)"
scr_3_y="$(printf '%s\n' "$xrandr_output"    | \grep "^$scr_3_name" | awk '{print $3}' | cut -d '+' -f 1 | cut -d 'x' -f 2)"

scr_all_res="$(printf '%s\n' "$xrandr_output" | \grep -iw 'current' | awk '{print $8 "" $9 "" $10}' | tr -d ',')"                    ## <--,
scr_all_x="$(printf '%s\n' "$xrandr_output"   | \grep -iw 'current' | awk '{print $8 "" $9 "" $10}' | tr -d ',' | cut -d 'x' -f 1)"  ## <--|-- NOTE do NOT replace " with ' in awk
scr_all_y="$(printf '%s\n' "$xrandr_output"   | \grep -iw 'current' | awk '{print $8 "" $9 "" $10}' | tr -d ',' | cut -d 'x' -f 2)"  ## <--'

# scr_1_brightness="$(printf '%02d\n' "$(( "$(< /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-"$scr_1_name"/intel_backlight/brightness)" * 200 / 187 / 2 ))")"
## OR:
# "$(xbacklight | cut -d '.' -f 1)"
