#!/usr/bin/env bash

## @last-modified 1400-10-12 18:20:09 +0330 Sunday

## NOTE this file is used a. for making docker image, and b. in action-jcal

function dl_xtract {
    mkdir -p "$temp_dir"/sources
    wget -qO "$temp_dir"/jcal_latest.tar.gz "$1"
    tar -xf "$temp_dir"/jcal_latest.tar.gz -C "$temp_dir"/sources
}

## needed because user is root when creating docker image, and non-root in GitHub Actions
(( EUID == 0 )) && is_root='true'

temp_dir="$(mktemp --directory)"

printf 'installing dependencies\n'
for dep in automake build-essential libjalali-dev libtool; {
    [ "$(which "$dep")" ] && continue
    if [ "$is_root" == 'true' ]; then
        printf 'installing %s as root\n' "$dep"
        apt install -y --no-install-recommends "$dep"
    else
        printf 'installing %s as non-root\n' "$dep"
        sudo apt install -y --no-install-recommends "$dep"
    fi
}

printf 'cloning/downloading\n'
case "$1" in
  'clone-github' ) git clone https://github.com/ashkang/jcal.git "$temp_dir" ;;
  'clone-gnu' ) git clone https://git.savannah.gnu.org/git/jcal.git "$temp_dir" ;;
  'gnu' ) dl_xtract 'http://download-mirror.savannah.gnu.org/releases/jcal/jcal-latest.tar.gz' ;;
  'askapache' ) dl_xtract 'http://nongnu.askapache.com/jcal/jcal-latest.tar.gz' ;;
  * ) printf 'invalid source\n'; exit 1 ;;
esac

printf 'installing\n'
cd "$temp_dir"/sources || exit 1  ## have to cd because absolute paths won't work
./autogen.sh
./configure
make
make install
/sbin/ldconfig
