#!/usr/bin/env bash
source "$HOME"/scripts/gb

#https://askubuntu.com/questions/637074/how-to-merge-multiple-more-than-two-videos-on-ubuntu

trap 'rm *.ts 2>/dev/null' EXIT

function help(){ source "$HOME"/scripts/.help; join_intro_outtro_help ;}

function prompt(){
    for args in "$@"; do
        case "$1" in
            -d ) [ ! "$dir" ] && get_input "Dir (e.g. v-Lucy)" && dir="$input" ;;
        esac
        shift
    done ;}

function line(){ echo -e "$(grey "$(printf "%$(tput cols)s\n" | sed "s/ /▬/g")")" ;}

while getopts 'hd:' flag; do
    case "$flag" in
        h ) help          ;;
        d ) dir="$OPTARG" ;;
    esac
done

title="${0##*/}"
heading "$title"

main_items=( "join intro-outtro" "help" )
main_item="$(pipe_to_fzf "${main_items[@]}")" && wrap_fzf_choice "$main_item" || exit 37

case "$main_item" in
    "join intro-outtro" ) total_start="$(get_datetime "jseconds")"
                          prompt -d
                          [ ! -d "$HOME"/website/Files/"$dir" ] && red " No such dir" && exit

                          intro="$HOME"/io/intros/"$dir".mp4
                          intro_ts="0-intro.ts"
                          outtro="$HOME"/io/outtro/outtro.mp4
                          outtro_ts="0-outtro.ts"

                          [ ! -f "$intro"  ] && red " No such intro"  && exit
                          [ ! -f "$outtro" ] && red " No such outtro" && exit

                          cd "$HOME"/website/Files/"$dir"

                          action_now "creating $intro_ts & $outtro_ts"
                          ffmpeg -i "$intro"  -c copy -f mpegts "$intro_ts"  2>/dev/null
                          ffmpeg -i "$outtro" -c copy -f mpegts "$outtro_ts" 2>/dev/null
                          echo

                          vid_count=0
                          vids=( $(find . -mindepth 1 -maxdepth 1 -iname "*.mp4" | sort) )
                          for vid in "${vids[@]}"; do
                              video_start="$(get_datetime "jseconds")"
                              brown "$vid"
                              vid_ts="${vid}.ts"
                              ffmpeg -i "$vid" -c copy -f mpegts "$vid_ts" 2>/dev/null
                              ffmpeg -i "concat:${intro_ts}|${vid_ts}|${outtro_ts}" "${vid/.mp4/-JOINED.mp4}" 2>/dev/null && \
                              rm "$vid_ts"
                              ((vid_count++))
                              video_end="$(get_datetime "jseconds")"
                              dur="$(day_hour_min_sec "$(( "$video_end" - "$video_start" ))")"
                              blue "Video joining duration: $dur"
                              line
                          done
                          blue "$vid_count videos joined"
                          total_end="$(get_datetime "jseconds")"
                          dur="$(day_hour_min_sec "$(( "$total_end" - "$total_start" ))")"
                          blue "Total joining duration: $dur" ;;
    help ) help ;;
esac

exit
