#!/usr/bin/env bash

## last modified: 1400-09-02 23:12:01 Tuesday

case "$1" in
    rofi ) rofi -show combi & ;;
    dmenu ) dmenu_run -i -l "$dmenulines" -nb "$dmenunb" -nf "$dmenunf" -sb "$dmenusb" -sf "$dmenusf" -fn "$dmenufn" -p 'dmenu' & ;;
esac

exit
