#!/usr/bin/env bash

## @last-modified 1400-10-29 10:13:20 +0330 Wednesday

case "$1" in
    rofi )
        rofi -show combi & ;;
    dmenu )
        dmenu_run -i -l "$dmenulines" -nb "$dmenunb" -nf "$dmenunf" -sb "$dmenusb" -sf "$dmenusf" -fn "$dmenufn" -p 'dmenu' & ;;
esac
