#!/usr/bin/env bash

## last modified: 1400-09-02 23:12:01 Tuesday

source "$HOME"/scripts/gb

title="${0##*/}"

function display_help {
    source "$HOME"/scripts/.help
    mime_type_help
}

function prompt {
    for args in "$@"; {
        case "$1" in
            -n ) [ ! "$name" ] && get_input 'Dir/fie name' && name="$input" ;;
        esac
        shift
    }
}

function get_opt {
    local options="$(getopt -l 'help,name:' -o 'hn:' -a -- "$@")"
    eval set -- "$options"
    while true; do
        case "$1" in
            -h|--help ) display_help     ;;
            -n|--name ) shift; name="$1" ;;
            -- )        break            ;;
        esac
        shift
    done
}

get_opt "$@"
heading "$title"

main_items=( 'mime-type' 'help' )
main_item="$(pipe_to_fzf "${main_items[@]}")" && wrap_fzf_choice "$main_item" || exit 37

case "$main_item" in
    mime-type ) prompt -n
                file --mime-type "$name" -bL && accomplished
                exit ;;
    help ) display_help ;;
    * ) exit ;;
esac

exit
