#!/usr/bin/env bash

## @last-modified 1400-10-29 10:31:09 +0330 Wednesday

source "$HOME"/scripts/gb
source "$HOME"/scripts/gb-audacious

function no_such_file {
    msgc 'ERROR' "no such file as <span color=\"${orange}\">\$HOME/movie/${directory}/${movie}</span>" "$HOME"/linux/themes/alert-w.png
    exit
}

function success_moving {
    local text

    text="$(printf "moved to <span color=\"%s\">WATCHED</span>\n<span color=\"%s\">%s</span>\n" "$blue" "$orange" "$base")"
    msgn "$text" '' "$HOME"/linux/themes/delete-w.png
}

function error_moving {
    msgc 'ERROR' "moving <span color=\"${orange}\">${base}</span> to <span color=\"${blue}\">WATCHED</span>" "$HOME"/linux/themes/alert-w.png
    # exit  ## exceptionally commented
}

function success_removing {
    msgn 'removed' "<span color=\"${red}\"><b>${base}</b></span>" "$HOME"/linux/themes/delete-w.png
}

function error_removing {
    msgc 'ERROR' "removing <span color=\"${orange}\">${base}</span>" "$HOME"/linux/themes/alert-w.png
}

function if_empty {  ## JUMP_1 the same used in "$HOME"/scripts/speech
    local count

    read count directory <<< "$directory"  ## 8 pargar

    ## check if count is an int
    [ "$count" -eq "$count" ] || {
        msgc 'ERROR' "<span color=\"${orange}\">${count}</span> is invalid count" "$HOME"/linux/themes/alert-w.png
        exit
    }

    (( count > 0 )) || {
        msgn 'nothing here'
        exit
    }
}

function if_dir {  ## JUMP_1
    [ -d "$HOME"/movie/"$directory" ] || {
        msgc 'ERROR' "no such directory as <span color=\"${orange}\">\$HOME/movie/${directory}</span>" "$HOME"/linux/themes/alert-w.png
        exit
    }
}

declare -a directories_plus_count

[ "$play_status" == 'playing' ] && continue_playing='true' || continue_playing='false'

[ "$1" ] || exit
[ "$1" == 'random' ] && title='random movie' || title='select movie'

readarray -t directories < <(find "$HOME"/movie -mindepth 1 -maxdepth 1 -type d | sort)

## get movie count in each directory and prepend it to the directory name
for tmp_directory in "${directories[@]}"; {
    movies_count="$(wc -l < <(find "$tmp_directory" -mindepth 1 -maxdepth 1 -type f ! -iname '*.srt'))"

    ## decide how many spaces to add
    if (( movies_count < 10 )); then
        spaces="       "
    elif (( movies_count < 100 )); then
        spaces="     "
    else
        spaces="   "
    fi
    directories_plus_count+=( "${movies_count}${spaces}${tmp_directory##*/}" )
}

directory="$(pipe_to_rofi "${directories_plus_count[@]}" "header=${title}")" || exit 37
if_empty  ## NOTE if_empty must precede if_dir
if_dir

case "$1" in
    random )
        movie="$(shuf -n 1 < <(find "$HOME"/movie/"$directory" -mindepth 1 -maxdepth 1 -type f ! -iname '*.srt'))"
        movie="${movie##*/}" ;;
    select )
        readarray -t movies < <(find "$HOME"/movie/"$directory" -mindepth 1 -maxdepth 1 -type f ! -iname '*.srt' | sort)
        movie="$(pipe_to_rofi "${movies[@]##*/}" "header=${directory}")" || exit 37 ;;
    * )
        exit ;;  ## NOTE do NOT remove
esac

## play
base="${movie%.*}"
msgn 'playing' "<span color=\"${orange}\">${base}</span>" "$HOME"/linux/themes/filmroll-w.png
[ -f "$HOME"/movie/"$directory"/"$movie" ] || no_such_file
vlc -f --play-and-exit -- "$HOME"/movie/"$directory"/"$movie" 2>/dev/null

## move to WATCHED or remove
what_to_dos=( '' 'mv to WATCHED' 'remove' )
what_to_do="$(pipe_to_rofi "${what_to_dos[@]}" "header=${movie}" 'bg=red')"  # || exit 37  ## the exit is exceptionally commented

case "$what_to_do" in
    'mv to WATCHED' )
        [ -d "$HOME"/movie/"$directory"/WATCHED ] || mkdir "$HOME"/movie/"$directory"/WATCHED
        mv "$HOME"/movie/"$directory"/"$movie" "$HOME"/movie/"$directory"/WATCHED && success_moving || error_moving ;;
    remove )
        rm "$HOME"/movie/"$directory"/"$movie" && success_removing || error_removing ;;
    # * )  ## NOTE keep commented
    #     exit ;;
esac

## play audacious if it was playing before the video was played
[ "$continue_playing" == 'true' ] && "$HOME"/scripts/awesome-widgets audacious play_pause
