#!/usr/bin/env bash

## last modified: 1400-09-02 23:12:01 Tuesday

source "$HOME"/scripts/gb
source "$HOME"/scripts/gb-audacious

function no_such_dir {
    msgc 'ERROR' "no such directory as <span color=\"${orange}\">\$HOME/music/${directory}</span>" "$HOME"/linux/themes/delete-w.png
    exit
}

function update_audacious {
    "$HOME"/scripts/awesome-widgets audacious
}

readarray -t directories < <(find "$HOME"/music -mindepth 1 -maxdepth 1 -type d | sort)
directory="$(pipe_to_rofi "${directories[@]##*/}" 'music' '')" || exit 37

[ ! -d "$HOME"/music/"$directory" ] && no_such_dir

turn_on_shuffle; sleep 0.1
clear_playlist ; sleep 0.1

msgn 'playing' "<span color=\"${orange}\">${directory}</span>" "$HOME"/linux/themes/musical-note-w.png

readarray -t files < <(find "$HOME"/music/"$directory" -mindepth 1 -type f -iname '*.mp3' | sort)  ## <--,-- -maxdepth 1 is not needed here
audacious -E "${files[@]}"                                                                         ##    |-- NOTE do NOT add cut -c 3- (it would open multiple error boxes
update_audacious                                                                                   ##    '-- saying 'Error reading *****. No such file or directory')

exit
