#!/usr/bin/env bash
source "$HOME"/scripts/gb
source "$HOME"/scripts/gb-audacious

function no_such_dir(){ msgc "ERROR" "no such directory as <span color=\"${orange}\">\$HOME/speech/${directory}</span>" "$HOME"/linux/themes/delete-w.png && exit ;}

function update_audacious(){ "$HOME"/scripts/awesome-widgets audacious ;}

cd "$HOME"/music
directories=( $(find . -mindepth 1 -maxdepth 1 -type d | cut -c 3- | sort) )
directory="$(pipe_to_dmenu "${directories[@]}" "music" "")" || exit 37

[ ! -d "$HOME"/music/"$directory" ] && no_such_dir || cd "$HOME"/music/"$directory"

if_speech      ; sleep 0.1
turn_on_shuffle; sleep 0.1
clear_playlist ; sleep 0.1

msgn "playing" "<span color=\"${orange}\">${directory}</span>" "$HOME"/linux/themes/musical-note-w.png

files=( $(find . -mindepth 1 -type f -iname "*.mp3" | sort) )  ## <--,-- -maxdepth 1 is not needed here
audacious -E "${files[@]}"                                     ##    '-- do NOT add cut -c 3- (it opens error boxes saying "Error reading *****. No such file or directory")
update_audacious

exit
