#!/usr/bin/env bash

## last modified: 1400-09-16 21:54:32 +0330 Tuesday

cmd='wget -qO - https://api.ipify.org'  ## https://github.com/rkienjet/torscripts/blob/master/newcircuit
## OR:
    # curl -s http://myip.enix.org/REMOTE_ADDR
    # curl ipinfo.io

printf 'Normal:\n\n'
eval "$cmd"
printf '\n'

printf '++++++++++++++++++\n'

printf 'Tor\n\n'
cmd="torsocks $cmd"
eval "$cmd"
printf '\n'
