#!/usr/bin/env bash

## last modified: 1400-09-02 23:12:01 +0330 Tuesday

printf '%s\n\n' 'Normal:'
curl ipinfo.io
## OR:
  # curl -s http://myip.enix.org/REMOTE_ADDR
  # wget -qO - https://api.ipify.org  ## https://github.com/rkienjet/torscripts/blob/master/newcircuit
printf '%s\n' '----------------------'
printf '%s\n\n' 'Tor:'
torsocks curl ipinfo.io
printf '\n'
