#!/usr/bin/env bash

## By Davoud Arsalani
##    https://github.com/davoudarsalani/scripts
##    https://github.com/davoudarsalani/scripts/blob/master/nuke
##    https://davoudarsalani.ir

## @last-modified 1400-10-27 09:10:39 +0330 Monday

## https://revelry.co/terminal-workflow-fzf/
## https://github.com/junegunn/fzf/wiki/examples

source "$HOME"/scripts/gb

IFS=$'\n'
if (( UID > 0 )); then
    readarray -t processes < <(ps -f -u "$UID")
else
    readarray -t processes < <(ps -ef)
fi
process="$(pipe_to_fzf "${processes[@]}")" && wrap_fzf_choice "$process" || exit 37

process="$(printf '%s\n' "$process" | awk '{print $2}')"

kill_prompt="$(get_single_input "Kill ${process}?")" && printf '\n'
case "$kill_prompt" in
    y ) [ "$process" ] && printf '%s\n' "$process" | xargs kill -9 ;;
esac
