#!/usr/bin/env bash

## last modified: 1400-09-08 10:53:14 +0330 Monday

## https://revelry.co/terminal-workflow-fzf/
## https://github.com/junegunn/fzf/wiki/examples

source "$HOME"/scripts/gb

IFS=$'\n'
if (( UID == 0 )); then
    readarray -t processes < <(ps -ef)
else
    readarray -t processes < <(ps -f -u "$UID")
fi
process="$(pipe_to_fzf "${processes[@]}")" && wrap_fzf_choice "$process" || exit 37

process="$(printf '%s\n' "$process" | awk '{print $2}')"

get_single_input "Kill ${process}?" && sure_prompt="$single_input"
case "$sure_prompt" in
    y ) [ "$process" ] && printf '%s\n' "$process" | xargs kill -9 ;;
esac
