#!/usr/bin/env bash

## By Davoud Arsalani
##    https://github.com/davoudarsalani/scripts
##    https://github.com/davoudarsalani/scripts/blob/master/todo
##    https://davoudarsalani.ir

## @last-modified 1401-07-15 09:24:24 +0330 Friday

source "$HOME"/scripts/gb

function cp_file_to_kaddy {
    cp "$file" "$kaddy_file"
}
file="$HOME"/todo/todo
kaddy_file="$HOME"/kaddy/todo/todo
readarray -t content < "$file"

main_items=( 'ADD' 'REMOVE' 'EMPTY' '' "${content[@]}" )
main_item="$(pipe_to_rofi "${main_items[@]}" 'header=todo')" || exit 37

case "$main_item" in
    ADD )
        declare -a add_items  ## no members needed here
        add_item="$(pipe_to_rofi "${add_items[@]}" 'header=add')" || exit 37

        ## exit if it already exists
        \grep -qw "$add_item" "$file" && msgc 'ERROR' "<span color=\"${orange}\">${add_item}</span> already exists" "$HOME"/linux/themes/alert-w.png && exit

        {
            printf '%s\n' "$add_item" >> "$file"
            cp_file_to_kaddy
        } && msgn "added <span color=\"${orange}\">${add_item}</span>" ;;
    REMOVE )
        [ "${content[0]}" ] || {
            msgc 'ERROR' 'todo is empty' "$HOME"/linux/themes/alert-w.png
            exit
        }

        # remove_items=  ## exceptionally skipped this line because we already have the content in the form of an array and can pipe it in the next line
        remove_item="$(pipe_to_rofi "${content[@]}" 'header=remove' 'bg=red')" || exit 37

        {
            sed -i "/^$remove_item$/d" "$file"  ## NOTE do NOT replace " with ' in sed
            cp_file_to_kaddy
        } && msgn "removed <span color=\"${red}\">${remove_item}</span>" ;;
    EMPTY )
        empty_items=( 'no' 'yes' )
        empty_item="$(pipe_to_rofi "${empty_items[@]}" 'header=you sure?')" || exit 37

        case "$empty_item" in
            yes )
                {
                    : > "$file"
                    cp_file_to_kaddy
                } && msgn 'emptied' ;;
        esac ;;
esac
