#!/usr/bin/env bash

## last modified: 1400-09-02 23:12:01 +0330 Tuesday

source "$HOME"/scripts/gb
source "$HOME"/scripts/gb-color

title="${0##*/}"

function display_help {
    source "$HOME"/scripts/.help
    user_help
}

function prompt {
    for args in "$@"; {
        case "$1" in
            -g ) [ ! "$group" ] && get_input 'Group' && group="$input" ;;
        esac
        shift
    }
}

function get_opt {
    local options="$(getopt -l 'help,group:' -o 'hg:' -a -- "$@")"
    eval set -- "$options"
    while true; do
        case "$1" in
            -h|--help )  display_help      ;;
            -g|--group ) shift; group="$1" ;;
            -- )         break             ;;
        esac
        shift
    done
}

get_opt "$@"
heading "$title"

main_items=( 'info' 'create group' "add $USER to a group" "remove $USER from a group" 'change login name' 'how to useradd' 'help' )
main_item="$(pipe_to_fzf "${main_items[@]}")" && wrap_fzf_choice "$main_item" || exit 37

case "$main_item" in
    info ) printf 'User/ID:\t\t%s/%s\n' "$(id -un)" "$(id -u)"  ## OR $EUID (for user ID)
           printf 'Groups:\t\t\t%s\n' "$(groups $(id -un))"
           printf 'Groups IDs:\t\t%s\n' "$(id -G)"
           printf 'Effective group ID:\t%s\n' "$(id -g)" && accomplished ;;
    'create group' ) prompt -g
                     sudo groupadd -r "$group" && accomplished ;;
    "add $USER to a group" ) prompt -g
                            sudo gpasswd -a "$USER" "$group" && accomplished ;;
    "remove $USER from a group" ) prompt -g
                                 sudo gpasswd -d "$USER" "$group" && accomplished ;;
    'change login name' ) red_blink 'Use tty logged in as root'
                          printf '%s\n' 'Syntax: usermod -l NEWNAME OLDNAME' ;;
    'how to useradd' ) printf '%s\t\t%s\n' "$(yellow 'Syntax:')" 'useradd -m -g <initial_group> -G <additional_groups> -s <login_shell> <username> (-m creates the user home directory as /home/<username>)'
                       printf '%s\t\t%s\n' "$(yellow 'e.g.:')" 'useradd -m -g users -G wheel,data,autologin -s /bin/bash/ jack' && accomplished ;;
    help ) display_help ;;
esac

exit
