#!/usr/bin/env bash

## By Davoud Arsalani
##    https://github.com/davoudarsalani/scripts
##    https://github.com/davoudarsalani/scripts/blob/master/wallpaper
##    https://davoudarsalani.ir

## @last-modified 1400-10-29 11:09:44 +0330 Wednesday

source "$HOME"/scripts/gb

current_wallpaper_file=/tmp/current_wallpaper

case "$1" in
    select )
        readarray -t wallpapers < <(find "$HOME"/wallpapers/ -mindepth 1 -maxdepth 1 -type f -iname '*.jpg' | sort)
        wallpaper="$(pipe_to_rofi "${wallpapers[@]##*/}" 'header=wallpaper')" || exit 37

        printf '%s\n' "$wallpaper" > "$current_wallpaper_file"
        feh --bg-fill "$HOME"/wallpapers/"$wallpaper" ;;
    random )
        random_wallpaper ;;
    current )
        cur_wall="$(< "$current_wallpaper_file")"
        text="$(printf "current wallpaper:\n<span color=\"%s\">%s</span>" "$orange" "$cur_wall")"
        msgn "$text" ;;
esac
