#!/usr/bin/env bash

## @last-modified 1400-10-29 11:12:34 +0330 Wednesday

source "$HOME"/scripts/gb

title="${0##*/}"

function display_help {
    source "$HOME"/scripts/.help
    website_create_audio_template_help
}

function prompt {
    for _ in "$@"; {
        case "$1" in
            -l )
                length="${length:-"$(get_input 'Length')"}" ;;
            -d )
                directory="${directory:-"$(get_input 'Directory')"}" ;;
            -p )
                per_page="${per_page:-"$(get_input 'Per page')"}" ;;
            -f )
                dest_file="${dest_file:-"$(get_input 'Destination file')"}" ;;
        esac
        shift
    }
}

function get_opt {
    local options

    options="$(getopt --longoptions 'help,length:,directory:,per-page:,destination-file:' --options 'hl:d:p:f:' --alternative -- "$@")"
    eval set -- "$options"
    while true; do
        case "$1" in
            -h|--help )
                display_help ;;
            -l|--length )
                shift
                length="$1" ;;
            -d|--directory )
                shift
                directory="$1" ;;
            -p|--per-page )
                shift
                per_page="$1" ;;
            -f|--destination-file )
                shift
                dest_file="$1" ;;
            -- )
                break ;;
        esac
    shift
    done
}

function separator {
    printf '<!-- wp:separator --><hr class=\"wp-block-separator\"/><!-- /wp:separator -->\n\n' >> "$dest_file"
}

function nextpage {
    [ "$n" == "$length" ] && return  ## to prevent inserting next page at the end
    printf '<!-- wp:nextpage --><!--nextpage--><!-- /wp:nextpage -->\n\n' >> "$dest_file"
}

get_opt "$@"
heading "$title"

prompt -l -d -p -f

for ((n=1; n<="$length"; n++)); do
    n3="$(printf "%03d" "$n")"
    printf '%s\n' "$n3"

    {
        ## audio player
        printf '<!-- wp:audio --><figure class=\"wp-block-audio\"><audio controls=\"\" src=\"https://www.dl.davoudarsalani.ir/DL/Audio/%s/%s.mp3\"></audio></figure><!-- /wp:audio -->' "$directory" "$n3"

        ## title
        printf '<!-- wp:pullquote --><figure class=\"wp-block-pullquote\"><blockquote><p></p></blockquote></figure><!-- /wp:pullquote -->\n\n'

        ## body
        printf '<!-- wp:paragraph --><p></p><!-- /wp:paragraph -->\n\n'
    } >> "$dest_file"

    ## separator or nextpage
    (( "$(( "$n" % "$per_page" ))" > 0 )) && separator || nextpage
done
