#!/usr/bin/env bash

## last modified: 1400-09-03 21:53:59 +0330 Wednesday

source "$HOME"/scripts/gb

title="${0##*/}"

function display_help {
    source "$HOME"/scripts/.help
    website_create_audio_template_help
}

function prompt {
    for args in "$@"; {
        case "$1" in
            -l ) [ ! "$length"    ] && get_input 'Length'                                             && length="$input"    ;;
            -d ) [ ! "$directory" ] && get_input 'Directory (e.g. TOEIC/Level-1 or 6-Minute-English)' && directory="$input" ;;
            -p ) [ ! "$per_page"  ] && get_input 'Per page'                                           && per_page="$input"  ;;
            -f ) [ ! "$dest_file" ] && get_input 'Destination file'                                   && dest_file="$input" ;;
        esac
        shift
    }
}

function get_opt {
    local options="$(getopt -l 'help,length:,directory:,per-page:,destination-file:' -o 'hl:d:p:f:' -a -- "$@")"
    eval set -- "$options"
    while true; do
        case "$1" in
            -h|--help )             display_help          ;;
            -l|--length )           shift; length="$1"    ;;
            -d|--directory )        shift; directory="$1" ;;
            -p|--per-page )         shift; per_page="$1"  ;;
            -f|--destination-file ) shift; dest_file="$1" ;;
            -- )                    break                 ;;
        esac
        shift
    done
}

function separator {
    printf '%s\n\n' "<!-- wp:separator --><hr class=\"wp-block-separator\"/><!-- /wp:separator -->" >> "$dest_file"
}

function nextpage {
    [ "$n" == "$length" ] && return  ## to prevent inserting next page at the end
    printf '%s\n\n' "<!-- wp:nextpage --><!--nextpage--><!-- /wp:nextpage -->" >> "$dest_file"
}

get_opt "$@"
heading "$title"

prompt -l -d -p -f

for ((n=1; n<="$length"; n++)); do
    n3="$(printf "%03d" "$n")"
    printf '%s\n' "$n3"

    ## audio player
    printf '%s\n\n' "<!-- wp:audio --><figure class=\"wp-block-audio\"><audio controls=\"\" src=\"https://www.dl.davoudarsalani.ir/DL/Audio/${directory}/${n3}.mp3\"></audio></figure><!-- /wp:audio -->" >> "$dest_file"

    ## title
    printf '%s\n\n' "<!-- wp:pullquote --><figure class=\"wp-block-pullquote\"><blockquote><p></p></blockquote></figure><!-- /wp:pullquote -->" >> "$dest_file"

    ## body
    printf '%s\n\n' "<!-- wp:paragraph --><p></p><!-- /wp:paragraph -->" >> "$dest_file"

    ## separator or nextpage
    [ "$(( "$n" % "$per_page" ))" == 0 ] && nextpage || separator
done

exit
