name: Black

on: [push, pull_request, workflow_dispatch]

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setting up python
      uses: actions/setup-python@v2
      # with:
      #   python-version: 3.9
      #   architecture: x64
    - name: Installing black
      shell: bash
      run: |
        pip install black
    - name: Checking scripts
      shell: bash
      run: |
        readarray -t text_files < <(find -mindepth 1 -maxdepth 1 -type f ! -iname 'thumbnail.jpg' | sort)
        readarray -t pythons    < <(printf '%s\n' "${text_files[@]}" | \grep -E '\.py$' | sort)
        for p in "${pythons[@]}"; {
          printf '%s\n' "$p"
          black --line-length 170 --skip-string-normalization --check -q "$p"
        }
