name: Black

on: [push, workflow_dispatch]

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install black
      shell: bash
      run: |
        pip install black
    - name: Checking with black
      run: |
        readarray -t text_files < <(find -mindepth 1 -maxdepth 1 -type f ! -iname 'thumbnail.jpg' | sort)
        readarray -t pythons    < <(printf '%s\n' "${text_files[@]}" | \grep -E '\.py$' | sort)
        for p in "${pythons[@]}"; {
          printf '%s\n' "$p"
          black --line-length 170 --skip-string-normalization --check -q "$p"
        }
