name:
  'Shellcheck'
on:
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run
      uses: davoudarsalani/shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC1091  # -e SC2034 -e SC1090
      with:
#         ignore_paths: ignoreme ignoremetoo
        ignore_names: '*.py' '*.md' 'thumbnail.jpg'
#       with:
#         severity: error
#       If you run into SC1090/SC1091 errors you may need to tell shellcheck to check all files at once:
#       with:
#         check_together: 'yes'
#       Run only in a single directory
#       with:
#         scandir: './scripts'
