name:
  'Shellcheck'
on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check
      uses: davoudarsalani/shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC1091 -e SC2154 -e SC2162  --color=always
        # SC1091 --> (info): Not following: *** was not specified as input (see shellcheck -x).
        # SC2154 --> warning: *** is referenced but not assigned
        # SC2162 --> note: read without -r will mangle backslashes.

